# API Keys & Services
# -------------------

# AI 智能搜索配置 (新增)
ai_search:
  api_key: "YOUR_AI_SEARCH_API_KEY"  # 您的 AI 搜索服务 API 密钥
  api_url: "YOUR_AI_SEARCH_API_URL"  # 您的 AI 搜索服务 API 端点 URL, e.g., "http://127.0.0.1:8004/api/videos/text"

# Pexels API配置
# 获取API Key: https://www.pexels.com/api/
pexels:
  api_host: "https://api.pexels.com"
  api_key: "YOUR_PEXELS_API_KEY"  # 替换为你的 Pexels API Key

# Pixabay API配置
# 获取API Key: https://pixabay.com/api/docs/
pixabay:
  api_host: "https://pixabay.com"
  api_key: "YOUR_PIXABAY_API_KEY"  # 替换为你的 Pixabay API Key

# LLM服务提供商配置
llm_providers:
  default: "siliconflow"  # 主要控制点：明确指定默认提供者

  ollama:
    enabled: false
    models:
      - "qwen3:14b-q8_0"
    host: "http://127.0.0.1:11434"
    remark: "本地模型服务，适用于关键词提取和场景分割"

  siliconflow:
    enabled: true
    api_key: "YOUR_SILICONFLOW_API_KEY"
    models:
      - "Qwen/Qwen3-14B"
      - "Qwen/Qwen3-8B"
    host: "https://api.siliconflow.cn/v1"
    remark: "硅基流动, 用于生成视频脚本和关键词"

  gemini:
    enabled: false
    api_key: "YOUR_GEMINI_API_KEY"
    models:
      - "gemini-1.5-pro-latest"
    remark: "Google Gemini，用作备用关键词提取方案"

  openai:
    enabled: false
    api_key: "YOUR_OPENAI_API_KEY"
    base_url: "YOUR_OPENAI_COMPATIBLE_ENDPOINT" # or your custom endpoint, e.g., https://api.openai.com/v1
    models:
      - "gemini-2.5-pro"
      - "gemini-2.5-flash"
      - "gemini-1.5-pro"
    remark: "OpenAI, for high-quality text generation"

# API服务器配置
api_server:
  secret_key: "CHANGE_THIS_TO_A_SECURE_KEY"  # 请修改为一个更长、更随机的安全密钥，例如通过密码管理器生成

# 视频输出设置
video:
  width: 1920
  height: 1080
  fps: 30
  subtitles:
    font_dir: "assets/fonts" # 包含自定义字体文件 (.ttf, .otf) 的目录的路径。 FFmpeg/libass 将会在此目录中查找字体。
    font_name: "港风繁体-方正粗宋繁体"
    font_size: 24
    primary_color: "&H00FFFFFF"
    outline_color: "&H00000000"
    border_style: 1
    outline: 1
    shadow: 0
    spacing: 0.5
    alignment: 2
    vertical_margin: 30 # 垂直边距 (像素)。对于底部对齐，这是字幕距离视频底部的距离。增加此值可将字幕向上推。

# 文件路径配置
paths:
  task_folder: "tasks"
  local_assets_dir: "storage/local"
  local_models: 
    base_path: "models"
    whisper: "whisper/faster-whisper-medium"
    sentence_transformer: 
      use_onnx: true
      path: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2-onnx"

# 素材搜索策略
asset_search:
  online_search_count: 5 # 每次在线搜索时，向Pexels或Pixabay请求的素材数量。
  max_keyword_retries: 3 # 在关键词用尽后，调用LLM生成新关键词的最大重试次数。
  request_delay_seconds: 3 # 两次在线API请求之间的最小间隔时间（秒）。
  fallback_en:
    - healthy lifestyle
    - wellness routine
    - exercise motion
  fallback_cn:
    - 健康生活方式
    - 养生日常
    - 运动镜头

# 场景检测参数
scene_detection:
  splitter:
    chunk_size: 50 # LLM一次处理的字幕行数。
    overlap: 10 # 区块之间的重叠行数，以确保上下文连续性。

# 提示词工程
prompts:
  scene_splitter: "assets/prompts/scene_splitter.yaml"
  keyword_generator: "assets/prompts/keyword_generator.yaml"
  asset_keyword_generator: "assets/prompts/asset_keyword_generator.yaml"

# 常规设置
debug: false # 设置为 true 以在视频合成时启用详细的 ffmpeg 日志，便于排查问题。

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

# TTS服务配置
tts_providers:
  default: "cosyvoice"
  
  cosyvoice:
    enabled: true
    base_endpoint: "YOUR_COSYVOICE_ENDPOINT" # e.g., "http://192.168.0.253:8002"
    api_key: "YOUR_COSYVOICE_API_KEY" # Optional, if your service requires an API key
    default_speaker: "台湾-中年医生-男"
    remark: "CosyVoice TTS service"

  siliconflow:
    enabled: false
    api_key: "YOUR_SILICONFLOW_TTS_API_KEY"
    host: "https://api.siliconflow.cn"
    models:
      - "FunAudioLLM/CosyVoice2-0.5B"
    default_speaker: "alex" # 可选: alex, anna, bella, benjamin, charles, claire, david, diana
    remark: "SiliconFlow TTS service"
