# API Keys & Services
# -------------------

# ==============================================================================
# AI 智能搜索配置 (新增)
# ==============================================================================
ai_search:
  # 您的 AI 搜索服务 API 密钥
  api_key: "123456"
  # 您的 AI 搜索服务 API 端点 URL
  api_url: "http://127.0.0.1:8004/api/videos/text"

# 前往 https://www.pexels.com/api/ 获取你的免费API Key
pexels:
  api_host: "https://api.pexels.com"
  api_key: "iNiHQpjN7TNllWGZxPztmUEx4StKko4CjJBq310RFPIlfiXPKZDxI6uk"

# 前往 https://pixabay.com/api/docs/ 获取你的免费API Key
pixabay:
  api_host: "https://pixabay.com"
  api_key: "51157807-3d36b78ae5b3cdfd0b119a2eb"

llm_providers:
  # 主要控制点：明确指定要使用的LLM提供者
  use: "ollama"  # 约定使用的LLM，代码中不再进行探测，唯一可用

  # LLM调用失败后的重试次数
  retries: 3

  ollama:
    # 约定LLM提供者中只有唯一的模型
    model: "qwen3:14b"
    host: "http://127.0.0.1:11434"
    remark: "本地模型服务，适用于关键词提取和场景分割"

  siliconflow:
    api_key: "sk-pvracxuykfnajymvqjyxxfmqiwfmqchlsasekahpilkysiiq"  # 请替换为您的 API Key
    # 约定LLM提供者中只有唯一的模型
    model: "Qwen/Qwen3-14B"
    host: "https://api.siliconflow.cn/v1"
    remark: "硅基流动, 用于生成视频脚本和关键词"

  openai:
    api_key: "gemini-litouge"
    base_url: "https://zwlxneivrfjr.us-east-1.clawcloudcloudrun.com/v1" # or your custom endpoint
    # 约定LLM提供者中只有唯一的模型
    model: "gemini-2.5-pro"
    remark: "OpenAI, for high-quality text generation"

# TTS (Text-to-Speech) Services
# -----------------------------
tts_providers:
  use: "cosyvoice"  # Specify the TTS provider to use
  # 单次TTS请求的最大文本长度（字符数）
  tts_max_chunk_length: 2000

  cosyvoice:
    endpoint: "http://192.168.0.253:8002"
    api_key: "123456" # Optional, if your service requires an API key
    speaker: "台湾-中年医生-男"
    speed: 0.95
    remark: "CosyVoice TTS service"

  siliconflow:
    api_key: "sk-htjixlgptkfgetortpskpbfwrbiyudkvbnouaufybeojjgms"
    endpoint: "https://api.siliconflow.cn"
    model: "FunAudioLLM/CosyVoice2-0.5B"
    speaker: "speech:tw-m-doctor:d1joilil401s7387r05g:mphxmkfljxdfxjxvscbm" #speech:tw-m-doctor:d1joilil401s7387r05g:mphxmkfljxdfxjxvscbm" # 可选:FunAudioLLM/CosyVoice2-0.5B：alex/anna/bella/benjamin/charles/claire, david, diana
    speed: 0.95
    remark: "SiliconFlow TTS service"

api_server:
  # API服务器的默认监听地址和端口
  host: "0.0.0.0"
  port: 9001
  # 有效的API访问令牌列表
  tokens:
    - "123456"
    - "654321"
  # API服务器的调试模式。设置为 true 时，会显示更详细的日志，包括底层网络错误。
  debug_mode: false

# Video Output Settings
# ---------------------
composition_settings:
  # (新增) 子场景（镜头）的最小持续时间（秒）。
  # LLM生成的所有子场景时长都不得低于此值。
  # 代码中也会有后处理逻辑，以确保最终所有镜头都满足此要求。
  min_duration: 3
  size: 
    width: 1920
    height: 1080
  fps: 30

video:
  width: 1920
  height: 1080
  fps: 30
  # 字幕样式配置 (可选)
  subtitles:
    # 包含自定义字体文件 (.ttf, .otf) 的目录的路径。
    # FFmpeg/libass 将会在此目录中查找字体。
    font_dir: "assets/fonts"
    # 要使用的字体名称 (必须是字体文件名或字体内部定义的名称)。
    font_name: "港风繁体-方正粗宋繁体"
    # 字幕的字体大小。
    font_size: 24
    # 字幕的主要颜色 (ASS格式，例如 &H00FFFFFF 表示白色)。
    primary_color: "&H00FFFFFF"
    # 边框/描边的颜色 (ASS格式, &H00000000 表示黑色)。
    outline_color: "&H00000000"
    # 边框样式。1=带阴影的边框, 3=不透明背景框。
    border_style: 1
    # 边框/描边的宽度 (像素)。
    outline: 1
    # 阴影的深度 (像素)。
    shadow: 0
    # 字符间距 (像素)。
    spacing: 0.5
    # 字幕对齐方式 (使用数字小键盘布局): 1=左下, 2=中下, 3=右下, 5=中中, 8=中上, etc.
    alignment: 2
    # 垂直边距 (像素)。对于底部对齐，这是字幕距离视频底部的距离。增加此值可将字幕向上推。
    vertical_margin: 30

# File Paths
# ----------
paths:
  task_folder: "tasks"
  # 你的本地视频素材库，下载的素材也会保存在这里。
  local_assets_dir: "storage/local"
  # 本地模型配置
  local_models: 
    base_path: "models"
    whisper: "whisper/faster-whisper-large-v2"
    sentence_transformer: 
      use_onnx: false
      path: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# Asset Search Strategy
# ---------------------
asset_search:
  # 每次在线搜索时，向Pexels或Pixabay请求的素材数量。
  # 增加此值可以提高找到合适素材的几率，但会消耗更多API配额。
  online_search_count: 10

  # 在关键词用尽后，调用Ollama生成新关键词的最大重试次数。
  # max_keyword_retries: 3

  # (新增) 两次在线API请求之间的最小间隔时间（秒）。
  # 用于防止因请求过于频繁而被服务商限制。
  request_delay_seconds: 3

  # 新增两组补齐关键词
  fallback_en:
    - healthy lifestyle
    - wellness routine
    - exercise motion
  fallback_cn:
    - 健康生活方式
    - 养生日常
    - 运动镜头

# Scene Detection Parameters
# --------------------------
# 用于阶段一的语义场景分割。
scene_detection:
  splitter:
    # LLM一次处理的字幕行数。
    chunk_size: 50
    # 区块之间的重叠行数，以确保上下文连续性。
    overlap: 10

# Prompt Engineering
# ------------------
# 用于指导大语言模型完成特定任务的提示词模板。
prompts:
  # 用于场景分割 (Stage 1)
  scene_splitter: "assets/prompts/scene_splitter.yaml"

  keyword_generator: "assets/prompts/keyword_generator.yaml"

  # 用于在素材搜索失败后生成新的关键词 (Stage 2 retry)
  asset_keyword_generator: "assets/prompts/asset_keyword_generator.yaml"

# General Settings
# ----------------
# 设置为 true 以在视频合成时启用详细的 ffmpeg 日志，便于排查问题。
debug: false

# (新增) 文本处理设置
text_processing:
  # 场景（即视频中的一个镜头）的目标文本长度（字符数）。
  # 预处理流程会尝试将文稿段落智能地合并或切分到这个长度左右。
  scene_target_length: 300

# Logging configuration.
logging:
  # Log level can be DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
